### PR TITLE
add proxy support needed for middleware config of connect sections

### PR DESCRIPTION
**Pull request by xdemocle**

### CODE REVIEW

**Comment by gr2m** [comment]
ping @ro-ka

**Comment by ro-ka** [comment]
Looks fine to me!
@gr2m You want to use Hoodiebot for publishing? Else I do a manual publish.

**Comment by gr2m** [comment]
@ro-ka we don't have the bot integration yet here, please publish, thanks @ro-ka

**Comment by ro-ka** [comment]
Released as `0.3.0`.

**Pull request merged**
